# =========================================================
# OptiBF - PHYSICAL PARETO FIGURES
# XGBoost vs RSM vs GLOBAL PHYSICAL MODEL
# =========================================================
#
# Reads the files generated by:
#     ml_rsm_global_physical_pareto.py
#
# Produces:
#   1) Global physical Pareto with candidate origin
#   2) Surrogate Pareto vs. physical Pareto comparison
#
# The plots intentionally avoid data labels over the points.
# =========================================================

from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data" / "ml_rsm_comparison"
GLOBAL_DIR = DATA_DIR / "global_physical_pareto"

REFERENCE_BF = 1.55877649
REFERENCE_DELTA = 28.12134928

OUT_DIR = GLOBAL_DIR / "figures"
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------
# LOAD
# ---------------------------------------------------------

all_physical = pd.read_csv(
    GLOBAL_DIR / "all_30000_physical_evaluated.csv"
)

global_pareto = pd.read_csv(
    GLOBAL_DIR / "global_physical_pareto.csv"
)

global_winwin = pd.read_csv(
    GLOBAL_DIR / "global_physical_pareto_winwin.csv"
)

xgb_pareto = pd.read_csv(
    DATA_DIR / "xgb_pareto.csv"
)

rsm_pareto = pd.read_csv(
    DATA_DIR / "rsm_pareto.csv"
)

# ---------------------------------------------------------
# FIGURE 1
# GLOBAL PHYSICAL PARETO + ORIGIN
# ---------------------------------------------------------

plt.figure(figsize=(10, 6))

plt.scatter(
    all_physical["BF_physical"],
    all_physical["Delta_BF_physical"],
    s=7,
    alpha=0.10,
    label="30,000 candidatos avaliados fisicamente",
)

# Global Pareto line
gp = global_pareto.sort_values("BF_physical")

plt.plot(
    gp["BF_physical"],
    gp["Delta_BF_physical"],
    linewidth=2.2,
    label="Pareto física global",
)

# Origin categories
origin_styles = {
    "RSM": {"marker": "s", "size": 65},
    "Both": {"marker": "D", "size": 75},
    "Neither": {"marker": "^", "size": 65},
    "XGBoost": {"marker": "o", "size": 65},
}

for origin, style in origin_styles.items():

    subset = gp[
        gp["Surrogate_Origin"] == origin
    ]

    if len(subset):

        plt.scatter(
            subset["BF_physical"],
            subset["Delta_BF_physical"],
            marker=style["marker"],
            s=style["size"],
            label=f"Pareto física — {origin}",
            zorder=5,
        )

# Win-Win points
plt.scatter(
    global_winwin["BF_physical"],
    global_winwin["Delta_BF_physical"],
    facecolors="none",
    edgecolors="black",
    linewidths=1.4,
    s=130,
    label="Win-Win físico",
    zorder=7,
)

# Reference
plt.scatter(
    REFERENCE_BF,
    REFERENCE_DELTA,
    marker="*",
    s=220,
    label="Referência",
    zorder=10,
)

# Boundaries
plt.axvline(
    REFERENCE_BF,
    linestyle="--",
    linewidth=1,
)

plt.axhline(
    REFERENCE_DELTA,
    linestyle="--",
    linewidth=1,
)

plt.xlabel("Brake Factor (BF)")
plt.ylabel("ΔBF (%)")
plt.title(
    "Pareto Física Global — Origem dos candidatos"
)

plt.grid(True, alpha=0.22)
plt.legend(fontsize=8, loc="best")
plt.tight_layout()

plt.savefig(
    OUT_DIR / "01_global_physical_pareto_origin.png",
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# ---------------------------------------------------------
# FIGURE 2
# SURROGATE PARETO vs PHYSICAL GLOBAL PARETO
# ---------------------------------------------------------

plt.figure(figsize=(10, 6))

# Predicted surrogate Pareto
plt.plot(
    xgb_pareto["BF_XGB"],
    xgb_pareto["Delta_BF_XGB"],
    marker="o",
    markersize=3,
    linewidth=1.4,
    label="XGBoost — Pareto prevista",
)

plt.plot(
    rsm_pareto["BF_RSM"],
    rsm_pareto["Delta_BF_RSM"],
    marker="s",
    markersize=3,
    linewidth=1.4,
    label="RSM — Pareto prevista",
)

# Physical global Pareto
plt.plot(
    gp["BF_physical"],
    gp["Delta_BF_physical"],
    linewidth=2.8,
    label="Modelo físico — Pareto global",
)

# Highlight physical Pareto origins
for origin, marker in [
    ("RSM", "s"),
    ("Both", "D"),
    ("Neither", "^"),
]:

    subset = gp[
        gp["Surrogate_Origin"] == origin
    ]

    if len(subset):

        plt.scatter(
            subset["BF_physical"],
            subset["Delta_BF_physical"],
            marker=marker,
            s=55,
            zorder=6,
            label=f"Física — {origin}",
        )

# Reference
plt.scatter(
    REFERENCE_BF,
    REFERENCE_DELTA,
    marker="*",
    s=220,
    label="Referência",
    zorder=10,
)

plt.axvline(
    REFERENCE_BF,
    linestyle="--",
    linewidth=1,
)

plt.axhline(
    REFERENCE_DELTA,
    linestyle="--",
    linewidth=1,
)

plt.xlabel("Brake Factor (BF)")
plt.ylabel("ΔBF (%)")
plt.title(
    "Pareto prevista × Pareto física global — XGBoost vs. RSM"
)

plt.grid(True, alpha=0.22)
plt.legend(fontsize=8, loc="best")
plt.tight_layout()

plt.savefig(
    OUT_DIR / "02_surrogate_vs_physical_pareto.png",
    dpi=300,
    bbox_inches="tight",
)

plt.close()

# ---------------------------------------------------------
# SUMMARY
# ---------------------------------------------------------

print("\n========================================")
print("PHYSICAL PARETO FIGURES GENERATED")
print("========================================")

print(f"Global physical Pareto: {len(global_pareto)}")
print(f"Global physical Win-Win: {len(global_winwin)}")

print("\nOrigin:")
print(
    global_pareto["Surrogate_Origin"]
    .value_counts()
    .to_string()
)

print("\nWin-Win origin:")
print(
    global_winwin["Surrogate_Origin"]
    .value_counts()
    .to_string()
)

print("\nFiles:")
print(
    OUT_DIR / "01_global_physical_pareto_origin.png"
)
print(
    OUT_DIR / "02_surrogate_vs_physical_pareto.png"
)

print("\n========================================")
print("COMPLETED")
print("========================================")
